options:
    type: INNODB
    collate: utf8_general_ci
    charset: utf8

User:
  actAs:
    Timestampable:
      name: created_at
      type: timestamp
      format: d-m-Y H:i:s
  columns:
    id:
      type: integer
      unsigned: true
      primary: true
      autoincrement: true
    username:
      type: string(50)
      notnull: true
    password:
      type: string(40)
      notnull: true
    email:
      type: string(50)
    language_id:
      type: integer
      unsigned: true
    created_at:
      type: timestamp
  relations:
    Language:
      local: language_id
      foreign: id

Language:
  columns:
    id:
      type: integer
      unsigned: true
      primary: true
      autoincrement: true
    name:
      type: string(50)
      notnull: true
  relations:
    Users:
      class: User
      foreign: language_id
      local: id
      type: many